#include "Timer0.h"

Timer0_ConfigType Timer0_configuration={
		TIMER0_PWM_PHASE_CORRECT,
		NORMAL_PORT_NON_PWM,
		CLEAR_OCO_ON_COMPARE_MATCH_NON_INVERTING,
		CLEAR_OCO_ON_COMPARE_MATCH_UP_COUNTING
};
