
#include "Timer1.h"


Timer1_ConfigType Timer1_configuration={
		TIMER1_NORMAL_MODE,
		NON_PWM_TOGGLE_OC1A_ON_COMPARE_MATCH,
		NON_PWM_TOGGLE_OC1B_ON_COMPARE_MATCH,
		FAST_PWM_CLEAR_OC1A_OC1B_ON_COMPARE_MATCH_NON_INVERTING,
		PHASE_CORRECT_PWM_CLEAR_OC1A_OC1B_ON_COMPARE_MATCH_UP_COUNTING
};
