/*
 * Timer1_Types.h
 *
 *  Created on: 19 Aug 2023
 *      Author: mosam
 */

#ifndef TIMER1_TYPES_H_
#define TIMER1_TYPES_H_

typedef enum{
	TIMER1_NORMAL_MODE,
	TIMER1_PWM_PHASE_CORRECT_8_BIT,
	TIMER1_PWM_PHASE_CORRECT_9_BIT,
	TIMER1_PWM_PHASE_CORRECT_10_BIT,
	TIMER1_CTC_MODE_OCR1A,
	TIMER1_FAST_PWM_8_BIT,
	TIMER1_FAST_PWM_9_BIT,
	TIMER1_FAST_PWM_10_BIT,
	TIMER1_PWM_PHASE_FREQUENCY_CORRECT_ICR1,
	TIMER1_PWM_PHASE_FREQUENCY_CORRECT_OCR1A,
	TIMER1_PWM_PHASE_CORRECT_ICR1,
	TIMER1_PWM_PHASE_CORRECT_OCR1A,
	TIMER1_CTC_MODE_ICR1A,
	TIMER1_RESERVED_MODE,
	TIMER1_FAST_PWM_ICR1,
	TIMER1_FAST_PWM_OCR1A,
}Timer1_ModeType;


typedef enum{
	NON_PWM_OC1A_DISCONNECTED,
	NON_PWM_TOGGLE_OC1A_ON_COMPARE_MATCH,
	NON_PWM_CLEAR_OC1A_ON_COMPARE_MATCH,
	NON_PWM_SET_OC1A_ON_COMPARE_MATCH
}Timer1_COMANonPwmType;

typedef enum{
	NON_PWM_OC1B_DISCONNECTED,
	NON_PWM_TOGGLE_OC1B_ON_COMPARE_MATCH,
	NON_PWM_CLEAR_OC1B_ON_COMPARE_MATCH,
	NON_PWM_SET_OC1B_ON_COMPARE_MATCH
}Timer1_COMBNonPwmType;

typedef enum{
	FAST_PWM_OC1A_OC1B_DISCONNECTED,
	FAST_PWM_TOGGLE_OC1A_ON_COMPARE_MATCH,
	FAST_PWM_CLEAR_OC1A_OC1B_ON_COMPARE_MATCH_NON_INVERTING,
	FAST_PWM_SET_OC1A_OC1B_ON_COMPARE_MATCH_INVERTING
}Timer1_COMModeFastPwmType;


typedef enum{
	PHASE_CORRECT_PWM_OC1A_OC1B_DISCONNECTED,
	PHASE_CORRECT_PWM_TOGGLE_OC1A_ON_COMPARE_MATCH,
	PHASE_CORRECT_PWM_CLEAR_OC1A_OC1B_ON_COMPARE_MATCH_UP_COUNTING,
	PHASE_CORRECT_PWM_SET_OC1A_OC1B_ON_COMPARE_MATCH_DOWN_COUNTING
}Timer1_COMPhaseCorrectPwmType;


typedef struct {
	Timer1_ModeType                                 mode;
	Timer1_COMANonPwmType                           OC1A_nonPwm;
	Timer1_COMBNonPwmType                           OC1B_nonPwm;
	Timer1_COMModeFastPwmType                       OC1AB_fastPwm;
	Timer1_COMPhaseCorrectPwmType                   OC1AB_phasePwm;
}Timer1_ConfigType;


typedef enum{
	TIMER1_NO_CLK_SOURCE,
	TIMER1_CLK_NO_PRESCALER,
	TIMER1_CLK_8,
	TIMER1_CLK_64,
	TIMER1_CLK_256,
	TIMER1_CLK_1024,
	TIMER1_EXTERNAL_CLK_FALLING_EDGE,
	TIMER1_EXTERNAL_CLK_RISING_EDGE
}Timer1_PrescalerType;


#endif /* TIMER1_TYPES_H_ */
