

#include "SevenSegment.h"

const SEV_ConfigType SEV_Configuration[NUMBER_OF_SEV_SEGMENT]={
		{{SEV1_LED_A_PIN,SEV1_LED_B_PIN,SEV1_LED_C_PIN,SEV1_LED_D_PIN,SEV1_LED_E_PIN,SEV1_LED_F_PIN,SEV1_LED_G_PIN},
		SEV1_CONNECTION_TYPE,
		 SEV1_ENABLE_PIN },
		{{SEV2_LED_A_PIN,SEV2_LED_B_PIN,SEV2_LED_C_PIN,SEV2_LED_D_PIN,SEV2_LED_E_PIN,SEV2_LED_F_PIN,SEV2_LED_G_PIN},
		SEV2_CONNECTION_TYPE,
		SEV2_ENABLE_PIN
		},
		{{SEV3_LED_A_PIN,SEV3_LED_B_PIN,SEV3_LED_C_PIN,SEV3_LED_D_PIN,SEV3_LED_E_PIN,SEV3_LED_F_PIN,SEV3_LED_G_PIN},
		SEV3_CONNECTION_TYPE,
		SEV3_ENABLE_PIN
		},
		{{SEV4_LED_A_PIN,SEV4_LED_B_PIN,SEV4_LED_C_PIN,SEV4_LED_D_PIN,SEV4_LED_E_PIN,SEV4_LED_F_PIN,SEV4_LED_G_PIN},
		SEV4_CONNECTION_TYPE,
		SEV4_ENABLE_PIN
		},
		{{SEV5_LED_A_PIN,SEV5_LED_B_PIN,SEV5_LED_C_PIN,SEV5_LED_D_PIN,SEV5_LED_E_PIN,SEV5_LED_F_PIN,SEV5_LED_G_PIN},
		SEV5_CONNECTION_TYPE,
		SEV5_ENABLE_PIN
		},
		{{SEV6_LED_A_PIN,SEV6_LED_B_PIN,SEV6_LED_C_PIN,SEV6_LED_D_PIN,SEV6_LED_E_PIN,SEV6_LED_F_PIN,SEV6_LED_G_PIN},
		SEV6_CONNECTION_TYPE,
		SEV6_ENABLE_PIN
		}
};
