

#include "SevenSegment.h"

const SEV_ConfigType SEV_Configuration[NUMBER_OF_LCDS]={
		{{SEV1_LED_A_PIN,SEV1_LED_B_PIN,SEV1_LED_C_PIN,SEV1_LED_D_PIN,SEV1_LED_E_PIN,SEV1_LED_F_PIN,SEV1_LED_G_PIN},
		SEV1_CONNECTION_TYPE,
		 SEV1_ENABLE_PIN },
		{{SEV2_LED_A_PIN,SEV2_LED_B_PIN,SEV2_LED_C_PIN,SEV2_LED_D_PIN,SEV2_LED_E_PIN,SEV2_LED_F_PIN,SEV2_LED_G_PIN},
		SEV2_CONNECTION_TYPE,
		SEV2_ENABLE_PIN
		}
};
